"""DB regeneration

Revision ID: 28898405635c
Revises: 
Create Date: 2025-04-22 20:18:29.794322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28898405635c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charts', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'charts', ['id'])
    op.drop_constraint('charts_models_id_fk', 'charts', type_='foreignkey')
    op.drop_constraint('charts_model_controls_id_fk', 'charts', type_='foreignkey')
    op.drop_constraint('charts_resources_id_fk', 'charts', type_='foreignkey')
    op.create_foreign_key(None, 'charts', 'resources', ['object_id'], ['id'])
    op.create_foreign_key(None, 'charts', 'model_controls', ['control_id'], ['id'])
    op.create_foreign_key(None, 'charts', 'models', ['model_id'], ['id'])
    op.create_unique_constraint(None, 'measures', ['id'])
    op.create_unique_constraint(None, 'model_controls', ['id'])
    op.drop_constraint('model_controls_models_id_fk', 'model_controls', type_='foreignkey')
    op.create_foreign_key(None, 'model_controls', 'models', ['model_id'], ['id'])
    op.create_unique_constraint(None, 'models', ['id'])
    op.drop_constraint('models_sub_area_id_fkey', 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'subject_areas', ['sub_area_id'], ['id'])
    op.create_unique_constraint(None, 'node_details', ['id'])
    op.create_foreign_key(None, 'node_details', 'nodes', ['node_id'], ['id'])
    op.alter_column('node_resources', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'node_resources', ['id'])
    op.drop_constraint('node_resources_res_id_fkey', 'node_resources', type_='foreignkey')
    op.drop_constraint('node_resources_node_id_fkey', 'node_resources', type_='foreignkey')
    op.drop_constraint('node_resources_models_id_fk', 'node_resources', type_='foreignkey')
    op.create_foreign_key(None, 'node_resources', 'nodes', ['node_id'], ['id'])
    op.create_foreign_key(None, 'node_resources', 'models', ['model_id'], ['id'])
    op.create_foreign_key(None, 'node_resources', 'resources', ['res_id'], ['id'])
    op.create_unique_constraint(None, 'nodes', ['id'])
    op.drop_constraint('nodes_model_controls_id_fk', 'nodes', type_='foreignkey')
    op.drop_constraint('nodes_model_id_fkey', 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'model_controls', ['control_id'], ['id'])
    op.create_foreign_key(None, 'nodes', 'models', ['model_id'], ['id'])
    op.create_unique_constraint(None, 'relations', ['id'])
    op.drop_constraint('relations_nodes_id_fk', 'relations', type_='foreignkey')
    op.drop_constraint('relations_nodes_id_fk_2', 'relations', type_='foreignkey')
    op.create_foreign_key(None, 'relations', 'nodes', ['source_id'], ['id'])
    op.create_foreign_key(None, 'relations', 'nodes', ['target_id'], ['id'])
    op.create_unique_constraint(None, 'resource_types', ['id'])
    op.alter_column('resources', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'resources', ['id'])
    op.drop_constraint('resources_resource_types_id_fk', 'resources', type_='foreignkey')
    op.drop_constraint('resources_sub_area_id_fkey', 'resources', type_='foreignkey')
    op.drop_constraint('resources_measures_id_fk', 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'resource_types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'resources', 'subject_areas', ['sub_area_id'], ['id'])
    op.create_foreign_key(None, 'resources', 'measures', ['measure_id'], ['id'])
    op.create_unique_constraint(None, 'subject_areas', ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'subject_areas', type_='unique')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key('resources_measures_id_fk', 'resources', 'measures', ['measure_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('resources_sub_area_id_fkey', 'resources', 'subject_areas', ['sub_area_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('resources_resource_types_id_fk', 'resources', 'resource_types', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'resources', type_='unique')
    op.alter_column('resources', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'resource_types', type_='unique')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.create_foreign_key('relations_nodes_id_fk_2', 'relations', 'nodes', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('relations_nodes_id_fk', 'relations', 'nodes', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'relations', type_='unique')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.create_foreign_key('nodes_model_id_fkey', 'nodes', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('nodes_model_controls_id_fk', 'nodes', 'model_controls', ['control_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'nodes', type_='unique')
    op.drop_constraint(None, 'node_resources', type_='foreignkey')
    op.drop_constraint(None, 'node_resources', type_='foreignkey')
    op.drop_constraint(None, 'node_resources', type_='foreignkey')
    op.create_foreign_key('node_resources_models_id_fk', 'node_resources', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('node_resources_node_id_fkey', 'node_resources', 'nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('node_resources_res_id_fkey', 'node_resources', 'resources', ['res_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'node_resources', type_='unique')
    op.alter_column('node_resources', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'node_details', type_='foreignkey')
    op.drop_constraint(None, 'node_details', type_='unique')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key('models_sub_area_id_fkey', 'models', 'subject_areas', ['sub_area_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'models', type_='unique')
    op.drop_constraint(None, 'model_controls', type_='foreignkey')
    op.create_foreign_key('model_controls_models_id_fk', 'model_controls', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'model_controls', type_='unique')
    op.drop_constraint(None, 'measures', type_='unique')
    op.drop_constraint(None, 'charts', type_='foreignkey')
    op.drop_constraint(None, 'charts', type_='foreignkey')
    op.drop_constraint(None, 'charts', type_='foreignkey')
    op.create_foreign_key('charts_resources_id_fk', 'charts', 'resources', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('charts_model_controls_id_fk', 'charts', 'model_controls', ['control_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('charts_models_id_fk', 'charts', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'charts', type_='unique')
    op.alter_column('charts', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
